set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" My Plugins
Plugin 'https://github.com/scrooloose/nerdtree.git' "Tree View
Plugin 'https://github.com/klen/python-mode.git' "Python
Plugin 'https://github.com/scrooloose/syntastic.git' "Syntax Highlighting for everything
Plugin 'https://github.com/godlygeek/tabular.git' "Tab alignment of stuff
Plugin 'https://github.com/tomtom/tlib_vim.git' "Some library stuff for other modules
Plugin 'https://github.com/MarcWeber/vim-addon-mw-utils.git' "Some library stuff for other modules
Plugin 'https://github.com/edkolev/tmuxline.vim.git' "Tmux line
Plugin 'https://github.com/rodjek/vim-puppet.git' "Puppet
Plugin 'https://github.com/tpope/vim-sensible.git' "Sensible defaults
Plugin 'https://github.com/garbas/vim-snipmate.git' "Snippit support
Plugin 'https://github.com/honza/vim-snippets.git' "Some default snippits
Plugin 'https://github.com/christoomey/vim-tmux-navigator.git' "Navigate with ctrl in tmux/vim
Plugin 'https://github.com/tomasr/molokai.git' "Color scheme
Plugin 'https://github.com/majutsushi/tagbar.git' "View Tags
Plugin 'https://github.com/easymotion/vim-easymotion.git' "Easymotion searching
Plugin 'https://github.com/xolox/vim-misc.git'

" The following are examples of different formats supported.

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Turn on syntax
syntax enable

" Turn on number
set number

" Highlight ugly tabs and whitespaces
highlight LiteralTabs ctermbg=darkgreen guibg=darkgreen
match LiteralTabs /\s\	/
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$/
highlight Normal ctermfg=grey ctermbg=black

" Vim airline fonts
let g:airline_powerline_fonts = 1

" Enable Mouse
set mouse=a

" Setup jj to be esc
inoremap jj <Esc>

" Remap leader to ',,'
let mapleader=","

" Tagbar
noremap <Leader>t :TagbarToggle<CR>

" Set Tabs
set tabstop=2 shiftwidth=2 expandtab

" Make neovim work with python virtual envs
let g:python_host_prog='/usr/bin/python'

" Use the clipboard
set clipboard=unnamedplus

" Setup tmuxline
let g:airline#extensions#tmuxline#enabled = 1
let airline#extensions#tmuxline#snapshot_file = "~/.tmux-status.conf"
